version: '2'
services:
  limesurvey:
    ports:
      - "8080:80"
    volumes:
      - mysql:/var/lib/mysql
      - upload:/app/upload
    image:
      cbarnett/limesurvey:2.55.2+166103
volumes:
  mysql:
  upload:
